version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - php
      - mysqldb
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/api:rw
  php:
    image: nanoninja/php-fpm:latest
    restart: always
    working_dir: /var/www/api
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/api
  mysqldb:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

